In [1]:
import numpy as np 

In [3]:
d = np.zeros(2)

In [4]:
d

array([0., 0.])

In [5]:
u = np.array([1, 4, 5, 7])

In [17]:
v = np.array([1, 0, 0, 2])

In [6]:
u

array([1, 4, 5, 7])

In [14]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [15]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [16]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]

])

In [21]:
v.shape[0]

4

In [25]:
def vector_vector_mult(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]
    return result
    

In [26]:
print(vector_vector_mult(u, v))

15.0


In [27]:
u.dot(v)

15

In [36]:
v.shape[0]

4

In [59]:
def matrix_vector_mult(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    result = np.zeros(num_rows)
    for i in range(num_rows):
        result[i] = vector_vector_mult(U[i], v)
    return result 


In [50]:
print(matrix_vector_mult(U, v))

[14.  5.  5.]


In [51]:
U.dot(v)

array([14,  5,  5])

In [62]:
def matrix_matrix_mult(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_mult(U, vi)
        result[:, i] = Uvi
    
    return result
        

In [63]:
matrix_matrix_mult(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [64]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity Matrix

In [67]:
I = np.eye(3)

In [69]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Inverse

In [70]:
Vs = V[[0, 1, 2]]

In [71]:
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [72]:
Vs_inv = np.linalg.inv(Vs)

In [73]:
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [74]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])